{
 "title": "System Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 -\n  node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay|squashfs|ramfs|efivarfs|proc|sysfs|cgroup2|devpts\"}\n  /\n  node_filesystem_size_bytes{fstype!~\"tmpfs|overlay|squashfs|ramfs|efivarfs|proc|sysfs|cgroup2|devpts\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}